frontend/src/app/assessment-form/assessment-form.component.html

Edited the double end date so it shows start date, end date now.

#38 changes to start/end date in assessment form

---

README.md
src/temp/seed-user.ts

Created functionality to simplify the initial user creation.  Furthermore, I updated the README with additional instructions on how to create the initial user.

Seed Initial User

---

frontend/src/app/navbar/navbar.component.html
frontend/src/app/navbar/navbar.component.sass

Fixes # 31
```release-note
- Corrected missing alt tag for the logo
- Corrected placement of the dropdown menu in navbar
```
---

Issue #31 - corrected menu dropdown location and alt tag for logo

---

.versionrc
package-lock.json
package.json

Fixes #42 
Installed [standard-version](https://github.com/conventional-changelog/standard-version) to help automate version control in conjunction with commitizen.  The new script `npm run release` will be ran on the master branch after every release from the `develop` branch.
---

chore(package.json): installed standard version

---

frontend/src/app/app.interceptor.ts
frontend/src/app/auth.service.ts
frontend/src/app/interfaces/Tokens.ts
frontend/src/app/login/login.component.ts
src/app.ts
src/middleware/jwt.middleware.ts
src/routes/authentication.controller.ts

Fixes #5 
This pull request contains the refresh token implementation which will allow a user to extend their session beyond the life of their authorization token (`authToken`).  With this implementation, the `authToken` has a expiry time limit of 15 minutes and the new `refreshToken` will have an expiry time of 8 hours.
---

Refresh Token Implementation

---

frontend/angular.json
frontend/src/app/register/register.component.html
frontend/src/app/register/register.component.ts
src/routes/user.controller.ts

Fixes #53 
The user profile functionality added new columns to the `User` table which include `firstName` `lastName`, and `Title`.  This inadvertently broke the login functionality.  This fix adds these missing fields to the registration form.  Existing users will have to be updated via the database.
---

Register form bug

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/app-routing.module.ts
frontend/src/app/app.module.ts
frontend/src/app/assessment-form/Assessment.ts
frontend/src/app/assessment-form/assessment-form.component.html
frontend/src/app/assessment-form/assessment-form.component.ts
frontend/src/app/classes/User.ts
frontend/src/app/report/report.component.html
frontend/src/app/user-profile/user-profile.component.ts
frontend/src/app/user.service.ts
frontend/src/styles.scss
src/app.ts
src/entity/Assessment.ts
src/routes/assessment.controller.ts
src/routes/user.controller.ts

Fixes #52 
The feature adds a new pick list to the assessment form when creating and updating assessments.  This field allows to associate a Bulwark user to the assessment so that their name and title is dynamically appended to the report.

Dynamic team

---

frontend/src/app/assessments/assessments.component.html
frontend/src/app/report/report.component.html

Fixes #3 
Added the UTC property to Angular datepipe so that it displays the correct dates on the assessments component and report component.
---

fix(angular datepipe): added UTC property to datepipe

---

CHANGELOG.md
package-lock.json
package.json
src/temp/seed-user.ts

Update Master from seed-user-bug

---

frontend/src/app/auth.service.ts
frontend/src/app/user-profile/user-profile.component.html
frontend/src/app/user-profile/user-profile.component.spec.ts
frontend/src/app/user-profile/user-profile.component.ts

Fixes #50 
The feature gives the ability for a user to update their password via their user profile.
---

Password update

---

CONTRIBUTING.md
TESTING.md
src/middleware/jwt.spec.ts

Added the Initial Test and Document to breakdown some of the testing requirements
Fixes #60 
```release-note
- Added jwt.middleware.ts test coverage
- Added TESTING.md document for testing information
```
---

Adding Initial Test + Added Document for testing.

---

.github/dependabot.yml

Add dependabot configuration to include both server and client dependencies
chore #65
Added [Dependabot](https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates) configuration to include both server and client dependencies.
---

chore(add dependabot config): add dependabot configuration

---

.github/workflows/node.js.yml

ci #6
Fixes #6 
Initial commit for CI Github action
---

ci(node.js.yml): initial commit for github action

---

.github/workflows/node.js.yml
package.json

Fixes #90 
Moved linting from the pre-commit hook to the Github action.
---

Moved linting to Github action

---

frontend/src/app/report/report.component.html

Implemented dynamic report properties that include the executive summary, problem locations,
resources, and screenshots.
Fixes #37

feat(report.component.html): implemented dynamic report properties

---

package-lock.json
package.json

Revert "chore(deps-dev): bump standard-version from 8.0.0 to 8.0.1"

---

package.json
src/temp/seed-user.spec.ts
src/temp/seed-user.ts

test(seed-user.ts): initial seed user test

---

frontend/src/app/app.service.ts
frontend/src/app/assessments/assessments.component.html
frontend/src/app/assessments/assessments.component.ts
frontend/src/app/vulnerability/vulnerability.component.html
frontend/src/app/vulnerability/vulnerability.component.ts
src/app.ts
src/middleware/jwt.middleware.ts
src/routes/assessment.controller.spec.ts
src/routes/assessment.controller.ts
src/routes/vulnerability.controller.ts

Fixes #177 
Implemented the ability to delete assessments.
---

Assessment Deletion Feature

---

frontend/src/app/assessments/assessments.component.html
src/routes/assessment.controller.spec.ts
src/routes/assessment.controller.ts

Fixes #205 
Added the Testers column to the assessment summary table so that it is easy to see which tester performed an assessment.
---

Add Testers column to Assessment Table in UI

---

CONTRIBUTING.md

The guidance was a little bit blurry, see https://github.com/softrams/bulwark/pull/244#pullrequestreview-478209869
```release-note
```
---

clearer PR target branch

---

frontend/src/app/assessments/assessments.component.html
frontend/src/app/assessments/assessments.component.ts

fixes #148 
Fix fontawesome faHaykal icon
```release-note
```
---

Fix fontawesome faHaykal icon

---

.github/workflows/node.js.yml
src/routes/user.controller.spec.ts

Added support to the CI to support running the backend tests.
Fixes #267 
```release-note
Added support for backend tests to run in the CI
```
---

Adding Backend tests support to CI

---

frontend/src/app/app.service.ts
frontend/src/app/dashboard/dashboard.component.html
frontend/src/app/dashboard/dashboard.component.ts
frontend/src/app/org-form/Organization.ts
frontend/src/app/org-form/org-form.component.html
frontend/src/app/org-form/org-form.component.ts
frontend/src/app/organization/organization.component.html
frontend/src/app/vulnerability/vulnerability.component.html
src/app.ts
src/database/migration/1601663481439-Refactor.ts
src/entity/Organization.ts
src/routes/asset.controller.spec.ts
src/routes/organization.controller.ts

Fixes #321 
Removed avatars from the dashboard in preparation for the dashboard refactor. 
---

Refactor dashboard to use PrimeNG table

---

frontend/src/app/app.module.ts
frontend/src/app/org-form/org-form.component.html
frontend/src/styles.scss

``` release-note
Refactor org-form.component.html to use PrimeNG's form components
```
---

feature: PrimeNG refactor Organization Form Component

---

frontend/src/app/app.module.ts
frontend/src/app/login/login.component.html
frontend/src/assets/theme/button.scss
frontend/src/styles.scss

Fixes #373  (issue)
```release-note
```
---

feat: login with prime ng

---

frontend/angular.json
frontend/package.json
frontend/src/app/app.module.ts
frontend/src/app/settings/settings.component.html
frontend/src/assets/theme/button.scss
frontend/src/styles.scss

Fixes #376 (issue)
```release-note
```
---

feat: settings with prime ng

---

frontend/src/app/app.module.ts
frontend/src/app/forgot-password/forgot-password.component.html
frontend/src/assets/theme/button.scss
frontend/src/styles.scss

Fixes #371  (issue)
```release-note
```
---

Feat: forgot password with prime ng

---

frontend/src/app/app.module.ts
frontend/src/app/email-validate/email-validate.component.html
frontend/src/assets/theme/button.scss
frontend/src/styles.scss

Fixes #370 (issue)
```release-note
```
---

Feat: prime ng email validate

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/app.module.ts
frontend/src/app/report/report.component.html
frontend/src/app/report/report.component.ts
package-lock.json

Fixes #410 
Implemented chart.js into the final reports.  The Tools & Methodology and OWASP Risk Rating table have been replaced with a pie chart and radar chart showing finding status and overall risk severity.
---
- [] My changes generate no new warnings

Reportchart

---

Dockerfile
bulwark_base/Dockerfile
bulwark_base/bulwark-entrypoint
docker-compose.yml

- [ x] Changes to our CI configuration files and scripts
```release-note
updated dockerfile as well as base docker container to speed up building and get ready for next iteration of bulwark.
internal testing elusive j issue resolved.
```
---
- [ x] My code follows the [contributing](../CONTRIBUTING.md) guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes …

Base image

---

frontend/src/app/report/report.component.html

Pulling in the vulnerability number/id as a feature request for #478
fix #478
```release-note
Add the numbering for fix 478.
```
---
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [] I have added tests that prove my fix is effective or that my feature works

feat(report component): numbered list for reports

---

frontend/package-lock.json
frontend/src/app/report/report.component.ts
package-lock.json

Adding the number of vulnerabilities next to the pie chart labels
fix #485
```release-note
Adding numbering to the pie chart.
```
---

feat(report component): add numbers to pie chart

---

.prettierignore
frontend/package-lock.json
frontend/src/app/report/report.component.html
frontend/src/app/report/report.component.sass

Fixes #489
- [ x] A bug fix
```release-note
Corrected reports creating a blank page at the end when no findings
```
---
- [ x] My code follows the [contributing](../CONTRIBUTING.md) guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit …

fix: no Vulns Blank page

---

.jest/setEnvVars.js
README.md
frontend/package-lock.json
frontend/src/app/administration/administration.component.html
frontend/src/app/apikey-management/apikey-management.component.html
frontend/src/app/apikey-management/apikey-management.component.spec.ts
frontend/src/app/apikey-management/apikey-management.component.ts
frontend/src/app/app.module.ts
frontend/src/app/auth.service.ts
frontend/src/app/interfaces/ApiKey.ts
frontend/src/app/user-management/user-management.component.html
frontend/src/app/user-profile/user-profile.component.html
frontend/src/app/user-profile/user-profile.component.ts
frontend/src/environments/environment.prod.ts
src/app.ts
src/entity/ApiKey.ts
src/entity/User.ts
src/middleware/jwt.middleware.ts
src/middleware/jwt.spec.ts
src/routes/api-key.controller.spec.ts
src/routes/api-key.controller.ts
src/routes/assessment.controller.spec.ts
src/routes/assessment.controller.ts
src/routes/asset.controller.spec.ts
src/routes/config.controller.spec.ts
src/routes/report-audit.controller.spec.ts
src/routes/team.controller.spec.ts
src/routes/user.controller.spec.ts
src/routes/vulnerability.controller.ts

Closes #483 
This pull request contains the API key generation feature.
---

API Key Support

---

frontend/src/app/vulnerability/vulnerability.component.html
src/routes/assessment.controller.spec.ts
src/routes/assessment.controller.ts
src/routes/asset.controller.spec.ts
src/routes/asset.controller.ts
src/routes/user.controller.ts
src/routes/vulnerability.controller.ts
src/utilities/puppeteer.utility.ts
src/utilities/role.utility.ts

Fixed BAC issues for asset, assessment, and vulnerability controllers.
---

Broken Access Control: Fix

---

README.md

fix #848
Fixes # (issue) 848
```release-note
Updating readme
```
---

docs(readme): readMe gifs in public AWS repo

---

.github/stale.yml

less aggressive stale policy

---

src/app.ts

Added missing middleware to the update password functionality which was causing the `req.user` to be
undefined.
fix #860
Fixes #860 860

fix(app.ts): fixed missing middleware for update password

---

frontend/src/app/app.module.ts
frontend/src/app/app.service.ts
frontend/src/app/organization/organization.component.html
frontend/src/app/organization/organization.component.ts
src/app.ts
src/routes/asset.controller.spec.ts
src/routes/asset.controller.ts

Closes #862 
Added vulnerability table to the assets table so that a user can view all open vulnerabilities against an asset.
---

Open Vulnerability Asset View

---

frontend/src/app/user-management/user-management.component.html
frontend/src/app/user-management/user-management.component.sass

User layout management fixes to hide the email address unless onhover
fix #878
```release-note
```
---
- [] I have made corresponding changes to the documentation

fix(user management): user management layout fixes

---

frontend/src/app/report/report.component.html

fix: report generation centering

---

README.md
frontend/src/environments/environment.prod.ts

Fixes #992
```release-note
Changes to port for Mac OS X Monterey from port 5000 to port 4500
```
---

Portchange

---

frontend/package-lock.json
frontend/package.json
package-lock.json
package.json
src/middleware/jwt.spec.ts

Fixes #994 
Hello again!  I had some time this weekend to dedicate some time to open source.  I made a couple small updates to fix the develop branch.  
1. Updated `@types/jasminewd2` version ^2.0.10 to get rid of build error
2. Updated `node-fetch` to fix import error
3. Skipped a single test in `jwt.spec.ts` that was causing repetitive failing requests and was using up Jest workers
4. Added `--runInBand` to the script `test:node` for quicker build times
Please note:  I did not run the application.  I just fixed the build process.  I recommend spinning up the …

Develop branch build fix

---

src/app.ts

Minor change.
```release-note
```
---

Duplicate spelling error

---

README.md

```release-note
- Updated README instructions.
```
---

Fix Read ME #1322

---

frontend/src/app/user-management/user-management.component.html
frontend/src/app/user-management/user-management.component.ts
frontend/src/app/user.service.ts
src/app.ts
src/routes/user.controller.ts

```release-note
Added ability to activate and deactivate in UI
```
---

Added ability to activate and deactivate in UI
